%% ALP Basic API, written by Salvatore Manfredi D'Angelo %%
% dmd_display sends an image to the DMD. It does not just load it in the memory, it also displays it.

% INPUTS:
    % dll_name_ = Loaded control library 
    % hdevice_ = device handle generated by allocate function 
    % image_ptr = pointer to the image you want to send on the DMD. Image must be uint8, with values until 255.
    % first_row = first row to be loaded (0) 
    % last_row = last row to be loaded (767)
    
% OUTPUT:
    % return_load and return_reset = Return for success/ error reporting

function [return_load,return_reset] = dmd_display(dll_name, hdevice, image_ptr, first_row, last_row)

first_row = int32(first_row);
last_row = int32(last_row);

[return_load,image] = calllib(dll_name, 'AlpbDevLoadRows', hdevice, image_ptr, first_row, last_row);
[return_reset] = calllib(dll_name, 'AlpbDevReset', hdevice, int32(4), int32(0)); %setting 4 and 0 there allows for global reset